set(USE_MKL OFF CACHE BOOL "Enable MKL")
if(USE_MKL)
    set(MKL_LINK static)
    if(WIN32)
        set(MKL_THREADING intel_thread)
        find_package(MKL REQUIRED)
    else()
        set(MKL_THREADING gnu_thread)
        find_package(MKL REQUIRED
        HINTS "/opt/intel/oneapi/mkl/latest/lib/cmake/mkl/")
    endif()
    #include_directories(${MKL_INCLUDE_DIR})
    #add_definitions(/DEIGEN_USE_MKL_ALL)
    add_definitions(/DMKL_ILP64)
    add_definitions(/DUSE_MKL)
    add_definitions(/DEIGEN_USE_BLAS)
    add_definitions(/DEIGEN_USE_MKL_VML)
endif()
